services:
  
  confnode:
    container_name: confnode
    image: mongo
    command: mongod --configsvr --replSet cfg --port 27017 --dbpath /data/db
    ports: 
      - 10003:27017
    volumes:
      - mongoshard:/data/db

  routernode:
    container_name: routernode
    image: mongo
    command: mongos --configdb cfg/confnode:27017 --port 27017 --bind_ip_all
    ports:
      - 10004:27017

  shardnode1: 
    container_name: shardnode1
    image: mongo
    command: mongod --shardsvr --replSet shardrs --port 27017 --dbpath /data/db
    ports: 
      - 10001:27017
    volumes:
      - mongoshard1:/data/db

  #PRIMARY:
  shardnode2:
    container_name: shardnode2
    image: mongo
    command: mongod --shardsvr --replSet shardrs --port 27017 --dbpath /data/db
    ports: 
      - 10002:27017
    volumes:
      - mongoshard2:/data/db
    
volumes:
  mongoshard:
  mongoshard1:
  mongoshard2:
