services:
  
  confnode:
    container_name: confnode
    image: mongo
    command: mongod --configsvr --replSet cfg --port 27017 --dbpath /data/db
    ports: 
      - 10005:27017
    volumes:
      - mongoshard:/data/db

  routernode:
    container_name: routernode
    image: mongo
    command: mongos --configdb cfg/confnode:27017 --port 27017 --bind_ip_all
    ports:
      - 10006:27017

  shard_1_node_1: #PRIMARY
    container_name: shard_1_node_1
    image: mongo
    command: mongod --shardsvr --replSet shard1 --port 27017 --dbpath /data/db
    ports: 
      - 10001:27017
    volumes:
      - mongoshard1_1:/data/db

  shard_1_node_2: 
    container_name: shard_1_node_2
    image: mongo
    command: mongod --shardsvr --replSet shard1 --port 27017 --dbpath /data/db
    ports: 
      - 10002:27017
    volumes:
      - mongoshard1_2:/data/db

  shard_2_node_1: #PRIMARY
    container_name: shard_2_node_1
    image: mongo
    command: mongod --shardsvr --replSet shard2 --port 27017 --dbpath /data/db
    ports: 
      - 10003:27017
    volumes:
      - mongoshard2_1:/data/db

  shard_2_node_2:
    container_name: shard_2_node_2
    image: mongo
    command: mongod --shardsvr --replSet shard2 --port 27017 --dbpath /data/db
    ports: 
      - 10004:27017
    volumes:
      - mongoshard2_2:/data/db
    
volumes:
  mongoshard:
  mongoshard1_1:
  mongoshard1_2:
  mongoshard2_1:
  mongoshard2_2:

