services:
  
  confnode:
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    ports: 
      - 10003:27017
    volumes:
      - mongoshard:/data/db

  routernode:
    image: mongo
    command: mongos --configdb cfgrs/configurationNode:27017 --port 27017
    ports:
      - 10004:27017

  ShardNode1:
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports: 
      - 10001:27017
    volumes:
      - mongoshard1:/data/db

  ShardNode2:
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports: 
      - 10002:27017
    volumes:
      - mongoshard2:/data/db

volumes:
  mongoshard:
  mongoshard1:
  mongoshard2:
